// Code-gen for the session protocol's TypeScript types.
//
// Source of truth: `tools/sim-flow/docs/flow/session-protocol.schema.json`
// (emitted by `cargo run -p sim-flow --bin session_protocol_schema`).
//
// Output: `src/session/protocol-types.ts` (committed; npm run compile
// regenerates so drift is impossible).
//
// Usage: `npm run codegen:protocol` (also runs as part of `npm run compile`).

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
// here = <repo>/tools/sim-flow/extensions/sim-flow-vscode/scripts
// → ../../../../.. = <repo>. Five levels because the extension lives
// under tools/sim-flow/ alongside prompts/ and templates/.
const repoRoot = process.env["SIM_FOUNDATION_ROOT"] ?? path.resolve(here, "..", "..", "..", "..", "..");
const schemaPath = path.join(
  repoRoot,
  "tools",
  "sim-flow",
  "docs",
  "flow",
  "session-protocol.schema.json",
);
const outPath = path.resolve(here, "..", "src", "session", "protocol-types.ts");

interface CommittedSchema {
  oneOf: Array<{ title: string; schema: Record<string, unknown> }>;
}

/**
 * `compile()` is invoked once per schema in the top-level oneOf and
 * each call inlines every type the schema references. Types that
 * appear in BOTH directions (e.g. `SessionKindOut` is used by
 * `Event::HelloAck.session.kind` and by `HostEvent::RunStep.kind`;
 * `StepMode` is used by `Event::StepModeChanged.mode` and by
 * `HostEvent::SetStepMode.mode`) are therefore emitted twice and
 * produce TS2300 "Duplicate identifier" errors when the file is
 * compiled.
 *
 * The duplicates are always single-line `export type X = ...;`
 * declarations — `compile()` handles cross-references for object /
 * union types via internal naming, so multi-line shapes only ever
 * appear once. We dedupe at the line level: any `export type X =
 * ...;` whose name was already emitted earlier in the concatenated
 * output is dropped, along with any preceding doc comment.
 */
function dedupeSingleLineTypeAliases(source: string): string {
  const lines = source.split("\n");
  const seen = new Set<string>();
  const keep: boolean[] = new Array(lines.length).fill(true);

  for (let i = 0; i < lines.length; i++) {
    // `export type X = "a" | "b";` (single-line literal-union form).
    // Multi-line `export type X =\n | { ... };` declarations are never
    // duplicated by `compile()` so they don't need this treatment.
    const m = lines[i].match(/^export type (\w+) = .+;$/);
    if (!m) continue;
    if (!seen.has(m[1])) {
      seen.add(m[1]);
      continue;
    }
    keep[i] = false;
    // Walk back over any immediately-preceding doc comment (`/** ... */`)
    // and strip it too — leaving the orphan would be visually confusing.
    let j = i - 1;
    if (j >= 0 && lines[j].trimEnd().endsWith("*/")) {
      while (j >= 0) {
        keep[j] = false;
        if (lines[j].trim().startsWith("/**")) break;
        j--;
      }
    }
  }

  return lines.filter((_, idx) => keep[idx]).join("\n");
}

async function main(): Promise<void> {
  const raw = await fs.readFile(schemaPath, "utf8");
  const top = JSON.parse(raw) as CommittedSchema;
  if (!Array.isArray(top.oneOf) || top.oneOf.length !== 2) {
    throw new Error(`unexpected schema shape at ${schemaPath}`);
  }

  const sections: string[] = [
    "// Auto-generated by scripts/generate-protocol-types.ts. Do not edit.",
    `// Source: tools/sim-flow/docs/flow/session-protocol.schema.json`,
    "// Run `npm run codegen:protocol` after touching the Rust enum.",
    "",
  ];

  for (const sub of top.oneOf) {
    const ts = await compile(sub.schema, sub.title.replace(/[^A-Za-z0-9]/g, "_"), {
      bannerComment: "",
      additionalProperties: false,
      enableConstEnums: false,
      style: { semi: true, singleQuote: false },
    });
    sections.push(`// ${sub.title}`);
    sections.push(ts.trim());
    sections.push("");
  }

  const combined = dedupeSingleLineTypeAliases(sections.join("\n"));
  await fs.writeFile(outPath, combined);
  console.log(`wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
