// Code-gen for the session protocol's TypeScript types.
//
// Source of truth: `tools/sim-flow/docs/flow/session-protocol.schema.json`
// (emitted by `cargo run -p sim-flow --bin session_protocol_schema`).
//
// Output: `src/session/protocol-types.ts` (committed; npm run compile
// regenerates so drift is impossible).
//
// Usage: `npm run codegen:protocol` (also runs as part of `npm run compile`).

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
// here = <repo>/tools/sim-flow/extensions/sim-flow-vscode/scripts
// → ../../../../.. = <repo>. Five levels because the extension lives
// under tools/sim-flow/ alongside prompts/ and templates/.
const repoRoot = process.env["SIM_FOUNDATION_ROOT"] ?? path.resolve(here, "..", "..", "..", "..", "..");
const schemaPath = path.join(
  repoRoot,
  "tools",
  "sim-flow",
  "docs",
  "flow",
  "session-protocol.schema.json",
);
const outPath = path.resolve(here, "..", "src", "session", "protocol-types.ts");

interface CommittedSchema {
  oneOf: Array<{ title: string; schema: Record<string, unknown> }>;
}

async function main(): Promise<void> {
  const raw = await fs.readFile(schemaPath, "utf8");
  const top = JSON.parse(raw) as CommittedSchema;
  if (!Array.isArray(top.oneOf) || top.oneOf.length !== 2) {
    throw new Error(`unexpected schema shape at ${schemaPath}`);
  }

  const sections: string[] = [
    "// Auto-generated by scripts/generate-protocol-types.ts. Do not edit.",
    `// Source: tools/sim-flow/docs/flow/session-protocol.schema.json`,
    "// Run `npm run codegen:protocol` after touching the Rust enum.",
    "",
  ];

  for (const sub of top.oneOf) {
    const ts = await compile(sub.schema, sub.title.replace(/[^A-Za-z0-9]/g, "_"), {
      bannerComment: "",
      additionalProperties: false,
      enableConstEnums: false,
      style: { semi: true, singleQuote: false },
    });
    sections.push(`// ${sub.title}`);
    sections.push(ts.trim());
    sections.push("");
  }

  await fs.writeFile(outPath, sections.join("\n"));
  console.log(`wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
