import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/**/*.test.ts"],
    environment: "node",
    coverage: {
      provider: "v8",
      // Only count first-party TypeScript under `src/`. Without an
      // explicit `include`, v8 reports against every file the tests
      // happened to load -- node_modules, generated `dist/` bundles,
      // protocol-types, etc. -- which dilutes the denominator into
      // tens of thousands of lines and makes the headline number
      // meaningless.
      include: ["src/**/*.ts"],
      exclude: [
        // Test files themselves shouldn't count toward source coverage.
        "src/**/*.test.ts",
        // Generated by `scripts/generate-protocol-types.ts`; covered
        // by the upstream schema's own tests, not ours.
        "src/session/protocol-types.ts",
        // Mock harness lives only to drive other tests.
        "src/mockFlowHarness.ts",
        "src/mockFlowHarness.test.ts",
      ],
      reporter: ["text", "text-summary", "html"],
    },
  },
});
