// Auto-generated by scripts/generate-protocol-types.ts. Do not edit.
// Source: tools/sim-flow/docs/flow/session-protocol.schema.json
// Run `npm run codegen:protocol` after touching the Rust enum.

// Event (orchestrator -> host)
/**
 * Event direction: orchestrator -> host.
 *
 * Serialized as a tagged JSON object with `event` carrying the variant name and the payload fields flattened next to it. We use kebab-case for the tag to match the JSON convention in the extension's existing types.
 */
export type Event =
  | {
      event: "hello-ack";
      protocol_version: string;
      session: SessionTag;
      sim_flow_version: string;
      step_descriptor: StepDescriptorOut;
    }
  | {
      event: "assistant-text";
      final_chunk: boolean;
      text: string;
    }
  | {
      event: "request-user-input";
      placeholder?: string | null;
      prompt?: string | null;
    }
  | {
      backend: string;
      debug_adaptation?: boolean;
      event: "request-llm-response";
      messages: LlmMessage[];
      model?: string | null;
      model_family_id?: string | null;
      request_id: string;
      runtime_profile_id?: string | null;
      /**
       * Tool catalog for backends that support native tool-use. Empty in M2; populated in M3.
       */
      tools?: LlmTool[];
    }
  | {
      bytes: number;
      event: "artifact-written";
      path: string;
    }
  | {
      args_summary: string;
      duration_ms: number;
      event: "tool-invoked";
      name: string;
      status: string;
    }
  | {
      event: "phase-changed";
      phase: string;
    }
  | {
      command: string;
      event: "build-output";
      exit_code: number;
      stderr_tail: string;
      stdout_tail: string;
    }
  | {
      clean: boolean;
      event: "gate-result";
      failures: GateFailureOut[];
      step: string;
    }
  | {
      event: "state-advanced";
      from: string;
      to?: string | null;
    }
  | {
      action: string;
      event: "followup";
      label: string;
    }
  | {
      event: "diagnostic";
      level: DiagnosticLevel;
      message: string;
    }
  | {
      event: "session-end";
      message?: string | null;
      reason: SessionEndReason;
    }
  | {
      event: "step-mode-changed";
      mode: StepMode;
    }
  | {
      event: "sub-session-started";
      kind: SessionKindOut;
      step: string;
    }
  | {
      event: "sub-session-ended";
      kind: SessionKindOut;
      outcome: string;
      step: string;
    };
/**
 * Mirror of `client::SessionKind` exposed in the protocol. Kept independent of the internal type so the wire format stays stable even if the internal representation changes.
 */
export type SessionKindOut = "work" | "critique";
export type LlmRole = ("system" | "user" | "assistant") | "tool";
export type DiagnosticLevel = "info" | "warning" | "error";
/**
 * Terminal state of a `SessionEnd` event. Closed-set enum so hosts can route on it deterministically (e.g. only re-enable Connect after `Completed`/`Cancelled`/`Error` but treat `RunawayGuard` as a hard abort that requires user attention). Serialized in kebab-case to match the existing wire strings.
 */
export type SessionEndReason =
  | "completed"
  | "cancelled"
  | "error"
  | "protocol-error"
  | "protocol-mismatch"
  | "runaway-guard";
/**
 * Step-axis mode of the orchestrator. Wire-stable enum serialized as `"auto"` / `"manual"`. See `docs/brainstorming/manual-step-mode.md`.
 */
export type StepMode = "auto" | "manual";

export interface SessionTag {
  candidate?: string | null;
  kind: SessionKindOut;
  step: string;
}
/**
 * Step descriptor sent in `HelloAck`. Same data as `sim-flow describe`'s output, but using protocol-stable field names.
 */
export interface StepDescriptorOut {
  flow: string;
  instruction_path: string;
  kind: SessionKindOut;
  per_candidate: boolean;
  /**
   * Per-step phases. M2 uses `["chat"]`; M3 expands for code steps to e.g. `["author", "build", "test", "coverage"]`.
   */
  phases: string[];
  predecessor_inputs: string[];
  prerequisite?: string | null;
  step: string;
  /**
   * Tool catalog the orchestrator will advertise to the LLM. Empty in M2; populated by step + kind in M3.
   */
  tools?: string[];
  work_artifacts: string[];
}
export interface LlmMessage {
  /**
   * Optional binary attachments associated with this message. Most messages have none; tool-output user messages may carry image bytes that the agent should treat as inline content (multimodal). The host (extension) is responsible for forwarding these to the underlying LLM via whatever multimodal API the backend supports; if the backend can't accept images the attachments are dropped and a Diagnostic is emitted.
   */
  attachments?: LlmAttachment[];
  content: string;
  role: LlmRole;
  /**
   * On `role = Tool` messages: the wire-side call id this message is replying to. Pairs with `LlmToolCall.id` from a prior `LlmEnd` so the model can match tool results to the calls that produced them. `None` on any other role. Backends without a tool-result wire shape (CLI agents, plain chat-completions without tool-use) flatten Tool-role messages into User-role text in their converter.
   */
  tool_call_id?: string | null;
  /**
   * On `role = Assistant` messages: the tool calls this turn emitted (echoed back on subsequent requests so the model sees its own prior calls in history). `None` when the turn produced no native tool calls or when the backend doesn't support them.
   */
  tool_calls?: LlmToolCall[];
}
export interface LlmAttachment {
  /**
   * Base64-encoded payload bytes. Hosts decode and forward to the LLM. Base64 is used because the protocol is JSONL.
   */
  data: string;
  /**
   * MIME type, e.g. "image/jpeg" or "image/png".
   */
  mime: string;
  /**
   * Project-relative source path, surfaced for tracing in logs. Optional because not every attachment originates from a file.
   */
  source?: string | null;
}
/**
 * A single tool call the model emitted in a native-tool-use turn. Returned on `HostEvent::LlmEnd.tool_calls`. `arguments_json` is the raw JSON-encoded argument blob the model emitted -- the orchestrator parses it into a `serde_json::Value` at dispatch time so a malformed payload surfaces a clear diagnostic rather than a cryptic serde error mid-pipeline.
 */
export interface LlmToolCall {
  arguments_json: string;
  id?: string | null;
  name: string;
}
/**
 * Tool catalog descriptor for a single advertised tool. Phase 9 M3 fills the `args_schema` with real JSON Schema for arg shapes.
 */
export interface LlmTool {
  /**
   * JSON Schema describing the tool's argument object.
   */
  args_schema: {
    [k: string]: unknown;
  };
  description: string;
  name: string;
}
export interface GateFailureOut {
  description: string;
  reason: string;
}

// HostEvent (host -> orchestrator)
/**
 * Event direction: host -> orchestrator.
 */
export type HostEvent =
  | {
      capabilities?: string[];
      event: "hello";
      host: HostInfo;
      protocol_version: string;
    }
  | {
      event: "user-message";
      text: string;
    }
  | {
      event: "llm-chunk";
      request_id: string;
      text: string;
    }
  | {
      event: "llm-end";
      request_id: string;
      stop_reason?: string | null;
      /**
       * Native tool calls the model emitted (when the backend supports native tool-use AND the orchestrator advertised a tool catalog on the matching `RequestLlmResponse`). Empty for fence-mode dispatches and for backends that don't support native tool calls. `#[serde(default)]` keeps the wire shape backward compatible with hosts that haven't been updated.
       */
      tool_calls?: LlmToolCall[];
    }
  | {
      event: "llm-error";
      kind: string;
      message: string;
      request_id: string;
    }
  | {
      action: string;
      event: "followup-selected";
    }
  | {
      event: "cancel";
    }
  | {
      event: "run-step";
      kind: SessionKindOut;
      step: string;
    }
  | {
      event: "run-critique";
      step: string;
    }
  | {
      event: "run-gate";
      step: string;
    }
  | {
      event: "advance";
      step: string;
    }
  | {
      event: "reset";
      step: string;
    }
  | {
      event: "set-step-mode";
      mode: StepMode;
    }
  | {
      event: "shutdown";
    };

export interface HostInfo {
  name: string;
  version: string;
}
/**
 * A single tool call the model emitted in a native-tool-use turn. Returned on `HostEvent::LlmEnd.tool_calls`. `arguments_json` is the raw JSON-encoded argument blob the model emitted -- the orchestrator parses it into a `serde_json::Value` at dispatch time so a malformed payload surfaces a clear diagnostic rather than a cryptic serde error mid-pipeline.
 */
export interface LlmToolCall {
  arguments_json: string;
  id?: string | null;
  name: string;
}
