// Auto-generated by scripts/generate-protocol-types.ts. Do not edit.
// Source: tools/sim-flow/docs/flow/session-protocol.schema.json
// Run `npm run codegen:protocol` after touching the Rust enum.

// Event (orchestrator -> host)
/**
 * Event direction: orchestrator -> host.
 *
 * Serialized as a tagged JSON object with `event` carrying the variant name and the payload fields flattened next to it. We use kebab-case for the tag to match the JSON convention in the extension's existing types.
 */
export type Event =
  | {
      event: "hello-ack";
      protocol_version: string;
      session: SessionTag;
      sim_flow_version: string;
      step_descriptor: StepDescriptorOut;
    }
  | {
      event: "assistant-text";
      final_chunk: boolean;
      text: string;
      tool_calls?: LlmToolCall[];
    }
  | {
      content: string;
      event: "llm-request";
      request_id: string;
      role: LlmRole;
      turn_index: number;
    }
  | {
      event: "request-user-input";
      placeholder?: string | null;
      prompt?: string | null;
    }
  | {
      bytes: number;
      event: "artifact-written";
      path: string;
    }
  | {
      args_summary: string;
      duration_ms: number;
      event: "tool-invoked";
      name: string;
      status: string;
    }
  | {
      event: "phase-changed";
      phase: string;
    }
  | {
      command: string;
      event: "build-output";
      exit_code: number;
      stderr_tail: string;
      stdout_tail: string;
    }
  | {
      clean: boolean;
      event: "gate-result";
      failures: GateFailureOut[];
      step: string;
    }
  | {
      event: "state-advanced";
      from: string;
      to?: string | null;
    }
  | {
      action: string;
      event: "followup";
      label: string;
    }
  | {
      event: "diagnostic";
      level: DiagnosticLevel;
      message: string;
    }
  | {
      event: "session-end";
      message?: string | null;
      reason: SessionEndReason;
    }
  | {
      event: "step-mode-changed";
      mode: StepMode;
    }
  | {
      event: "sub-session-started";
      kind: SessionKindOut;
      step: string;
    }
  | {
      event: "sub-session-ended";
      kind: SessionKindOut;
      outcome: string;
      step: string;
    };
/**
 * Mirror of `client::SessionKind` exposed in the protocol. Kept independent of the internal type so the wire format stays stable even if the internal representation changes.
 */
export type SessionKindOut = ("work" | "critique") | "qa";
export type LlmRole = ("system" | "user" | "assistant") | "tool";
export type DiagnosticLevel = "info" | "warning" | "error";
/**
 * Terminal state of a `SessionEnd` event. Closed-set enum so hosts can route on it deterministically (e.g. only re-enable Connect after `Completed`/`Cancelled`/`Error` but treat `RunawayGuard` as a hard abort that requires user attention). Serialized in kebab-case to match the existing wire strings.
 */
export type SessionEndReason =
  | "completed"
  | "cancelled"
  | "error"
  | "protocol-error"
  | "protocol-mismatch"
  | "runaway-guard";
/**
 * Step-axis mode of the orchestrator. Wire-stable enum serialized as `"auto"` / `"manual"`. See `docs/brainstorming/manual-step-mode.md`.
 */
export type StepMode = "auto" | "manual";

export interface SessionTag {
  candidate?: string | null;
  kind: SessionKindOut;
  step: string;
}
/**
 * Step descriptor sent in `HelloAck`. Same data as `sim-flow describe`'s output, but using protocol-stable field names.
 */
export interface StepDescriptorOut {
  flow: string;
  instruction_path: string;
  kind: SessionKindOut;
  per_candidate: boolean;
  /**
   * Per-step phases. M2 uses `["chat"]`; M3 expands for code steps to e.g. `["author", "build", "test", "coverage"]`.
   */
  phases: string[];
  predecessor_inputs: string[];
  prerequisite?: string | null;
  step: string;
  /**
   * Tool catalog the orchestrator will advertise to the LLM. Empty in M2; populated by step + kind in M3.
   */
  tools?: string[];
  work_artifacts: string[];
}
/**
 * A single tool call the model emitted in a native-tool-use turn. Returned on `HostEvent::LlmEnd.tool_calls`. `arguments_json` is the raw JSON-encoded argument blob the model emitted -- the orchestrator parses it into a `serde_json::Value` at dispatch time so a malformed payload surfaces a clear diagnostic rather than a cryptic serde error mid-pipeline.
 */
export interface LlmToolCall {
  arguments_json: string;
  id?: string | null;
  name: string;
}
export interface GateFailureOut {
  description: string;
  reason: string;
}

// HostEvent (host -> orchestrator)
/**
 * Event direction: host -> orchestrator.
 */
export type HostEvent =
  | {
      capabilities?: string[];
      event: "hello";
      host: HostInfo;
      protocol_version: string;
    }
  | {
      event: "user-message";
      text: string;
    }
  | {
      action: string;
      event: "followup-selected";
    }
  | {
      event: "cancel";
    }
  | {
      event: "run-step";
      kind: SessionKindOut;
      step: string;
    }
  | {
      event: "run-critique";
      step: string;
    }
  | {
      event: "run-gate";
      step: string;
    }
  | {
      event: "advance";
      step: string;
    }
  | {
      event: "reset";
      step: string;
    }
  | {
      event: "set-step-mode";
      mode: StepMode;
    }
  | {
      event: "shutdown";
    };

export interface HostInfo {
  name: string;
  version: string;
}
